### ISSUE TITLE
mamba reports archspec as x86_64-v3, but this feedstock expects it as x86_64_v3

### ISSUE THREAD

**Issue by traversaro** [conda-forge/microarch-level-feedstock#10]
### Comment:

I am not sure which one is correct, but I noticed an inconsistencies between `mamba` and this repo. This repo supports `x86_64_v3` as possible microarchitecture, but the `__archspec` value reported by mamba is instead `x86_64-v3` (the difference is last underscore that is a dash), see:
* https://github.com/mamba-org/mamba/blob/83fdeae46572a05a1657395cccccbab74e8710d3/libmamba/src/core/virtual_packages.cpp#L177-L191
* https://github.com/conda-forge/microarch-level-feedstock/blob/1b446dbab3999c5e27f1e0b000231f18fa1b6df1/recipe/conda_build_config.yaml#L15

As a consequence of this, the packages in this feedstock can't be installed via mamba/micromamba.

Related issue on the mamba side: https://github.com/mamba-org/mamba/issues/3222 .

fyi @conda-forge/microarch-level

**Comment by matthewfeickert** [comment]
@conda-forge/microarch-level I'm seeing this over on https://github.com/conda-forge/boost-histogram-feedstock/pull/57#issuecomment-2337101436 as well.

**Comment by traversaro** [comment]
The issue was fixed in https://github.com/mamba-org/mamba/pull/3404, I guess we actually need a release of mamba to actually fix it (or backport the patch to the mamba feedstock). fyi @conda-forge/micromamba @conda-forge/mamba

**Comment by matthewfeickert** [comment]
Things are fixed now: https://github.com/mamba-org/mamba/pull/3404#issuecomment-2369806701

**Comment by traversaro** [comment]
Yes, as of mamba 1.5.10 . The default miniforge3 installed probably still installs an older mamba in the base environment, so to use archspec-enabled packages make sure to run `conda update -n base mamba`.
